//Adding customers to database

package ams;

import java.awt.*; //Importing Abstract Windowing Toolkit
import java.awt.event.*; // Importing action event generated by awt
import javax.swing.*; // For GUI creation
import java.sql.*; // Importing to use mysql methods

public class Add_Customer extends JFrame // This class inherits from Jframe
{  
	JTextField textField,textField_1,textField_2,textField_3,textField_4,textField_5,textField_6; // various textfield declared

    public Add_Customer() // Making constructor for this class
    {
        getContentPane().setForeground(Color.BLUE);
        getContentPane().setBackground(Color.WHITE);
        setTitle("ADD CUSTOMER DETAILS");
		// Creating a heading of add customer details

        setDefaultCloseOperation(JFrame.HIDE_ON_CLOSE);
        setSize(778,486);
        getContentPane().setLayout(null);
        //Setting size of add customer and hiding it on close
			
        JLabel Passportno = new JLabel("PASSPORT NO");
        Passportno.setFont(new Font("Tahoma", Font.PLAIN, 17));
        Passportno.setBounds(60, 80, 150, 27);
        add(Passportno);
        //Jlabel for passport textfield
            
        textField = new JTextField();
        textField.setBounds(200, 80, 150, 27);
        add(textField);
		//setting dimensions of textfield

        JButton Next = new JButton("SAVE");
        Next.setBounds(200, 420, 150, 30);
        Next.setBackground(Color.BLACK);
        Next.setForeground(Color.WHITE);
        add(Next);
        //Creating Jbutton save and setting its dimension
			
        JLabel Pnrno = new JLabel("PNR NO");
        Pnrno.setFont(new Font("Tahoma", Font.PLAIN, 17));
        Pnrno.setBounds(60, 120, 150, 27);
        add(Pnrno);
        //Jlabel for pnr number and setting its dimension

        textField_1 = new JTextField();
        textField_1.setBounds(200, 120, 150, 27);
        add(textField_1);
        //creating textfield_1 and setting its dimension
            
        JLabel Address = new JLabel("ADDRESS");
        Address.setFont(new Font("Tahoma", Font.PLAIN, 17));
        Address.setBounds(60, 170, 150, 27);
        add(Address);
        //Jlabel for address and setting its dimension
			
        textField_2 = new JTextField();
        textField_2.setBounds(200, 170, 150, 27);
        add(textField_2);
        //creating textfield_2 and setting its dimension
            		
        JLabel Nationality = new JLabel("NATIONALITY");
        Nationality.setFont(new Font("Tahoma", Font.PLAIN, 17));
        Nationality.setBounds(60, 220, 150, 27);
        add(Nationality);
        //Jlabel for Nationality and setting its dimension
			
        textField_3 = new JTextField();
        textField_3.setBounds(200, 220, 150, 27);
        add(textField_3);
        //creating textfield_3 and setting its dimension
	
        JLabel Name = new JLabel("NAME");
        Name.setFont(new Font("Tahoma", Font.PLAIN, 17));
        Name.setBounds(60, 270, 150, 27);
        add(Name);
        //Jlabel for Name and setting its dimension
	
        textField_4 = new JTextField();
        textField_4.setBounds(200, 270, 150, 27);
        add(textField_4);
        //creating textfield_4 and setting its dimension
	
        JLabel Gender = new JLabel("GENDER");
        Gender.setFont(new Font("Tahoma", Font.PLAIN, 15));
        Gender.setBounds(60, 320, 150, 27);
        add(Gender);
        //Jlabel for Gender and setting its dimension
		
        JRadioButton NewRadioButton = new JRadioButton("Male");
        NewRadioButton.setBackground(Color.WHITE);
        NewRadioButton.setBounds(200, 320, 70, 27);
        add(NewRadioButton);
        //Option for selecting male

	
        JRadioButton Female = new JRadioButton("Female");
        Female.setBackground(Color.WHITE);
        Female.setBounds(280, 320, 70, 27);
        add(Female);
        //Option for selecting female
            
        JLabel Phno = new JLabel("PH NO");
        Phno.setFont(new Font("Tahoma", Font.PLAIN, 17));
        Phno.setBounds(60, 370, 150, 27);
        add(Phno);
        //Jlabel for Phno and setting its dimension
			
        textField_5 = new JTextField();
        textField_5.setBounds(200, 370, 150, 27);
        add(textField_5);
        //creating textfield_5 and setting its dimension
	
        setVisible(true);
	
        JLabel AddPassengers = new JLabel("ADD CUSTOMER DETAILS");
        AddPassengers.setForeground(Color.BLUE);
        AddPassengers.setFont(new Font("Tahoma", Font.PLAIN, 31));
        AddPassengers.setBounds(420, 24, 442, 35);
        add(AddPassengers);
        //Jlabel for Addpassengers and setting its dimension
    
        JLabel Flightcode = new JLabel("FLIGHT CODE");
        Flightcode.setFont(new Font("Tahoma", Font.PLAIN, 17));
        Flightcode.setBounds(60, 30, 150, 27);
        add(Flightcode);
        //Jlabel for Flightcode and setting its dimension

        textField_6 = new JTextField();
        textField_6.setBounds(200, 30, 150, 27);
        add(textField_6);
        //creating textfield_6 and setting its dimension
            
        ImageIcon i1 = new ImageIcon(ClassLoader.getSystemResource("ams/Images/Customer.png"));
        JLabel image = new JLabel(i1);
        image.setBounds(450,80,280,410);
        add(image);
        //Loading an icon from Images folder

            
        Next.addActionListener(new ActionListener() //Action is performed when button is clicked
        {
            public void actionPerformed(ActionEvent ae)
            {
                String passport_No = textField.getText();
                String pnr_no = textField_1.getText();
                String address =  textField_2.getText();
                String nationality = textField_3.getText();
                String name = textField_4.getText();
                String fl_code = textField_6.getText();
                   
                String gender = null;
                String ph_no = textField_5.getText();
                //Declaring string variables and storing the text which is returned from GUI
                    
                if(NewRadioButton.isSelected())
                {
                    gender = "male";
                    
                }
                else if(Female.isSelected())
                {
                        gender = "female";
                }
                // Condition to check either male or female is selected in radiobutton
                try 
                {
                    Connection conn;
                    Statement stat;
                    Class.forName("com.mysql.cj.jdbc.Driver");
                    conn=DriverManager.getConnection("jdbc:mysql://localhost:3306/ams", "root", "root");
                    // Connecting to database
                    stat=conn.createStatement();
                    String str = "INSERT INTO passenger values( '"+pnr_no+"', '"+address+"', '"+nationality+"','"+name+"', '"+gender+"', '"+ph_no+"','"+passport_No+"', '"+fl_code+"')";

                    stat.executeUpdate(str);
                    JOptionPane.showMessageDialog(null,"Customer Added");
                    setVisible(false);
                    //inserting values into database
                }
                catch (Exception e) 
                {
                    e.printStackTrace();// prints the exception
        	    }
		    }
        }
        );
			
        setSize(900,600);
        setVisible(true);
        setLocation(400,200);
			
	}  
    public static void main(String[] args)
    {
        new Add_Customer();
    }  // calling the constructor
}